fix: remove wrong condition from ZapConfig
project-chip/zap pull request #1385
Opened 2024-07-31 15:25 UTC by tbrkollar

2024-08-02 14:54 UTC, brdandu requested changes

2024-08-02 14:54 UTC, brdandu commented on src/pages/ZapConfig.vue
>          currentZapFileTemplatePacakges = this.currentZapFilePackages.filter(
currentZapFilePackages this didn't have typos here?

2024-08-02 14:54 UTC, brdandu commented on src/pages/ZapConfig.vue
> +      console.log(result.data.zapFilePackages)
Get rid of console.log

2024-08-02 14:54 UTC, brdandu commented on src/pages/ZapConfig.vue
> +      let currentTopLevelZapFilePackages = []
What about the changes to currentTopLevelZapFilePacakges.length below?

2024-08-02 14:54 UTC, brdandu commented on src/pages/ZapConfig.vue
> -      let currentZapFileTemplatePacakges = []
What about ` currentZapFileTemplatePacakges.map` below?

2024-08-02 19:25 UTC, paulr34 approved these changes

2024-08-05 13:20 UTC, brdandu approved these changes

2024-08-05 13:20 UTC, brdandu commented on cypress/e2e/theme/theme.cy.js
> +  it('Zigbee mode', () => {
From next time add a description on what the test is testing. Difficult to understand what this might be testing in the first go.

2024-08-05 13:27 UTC, merged