can go back to endpoint config from extensions and options page
project-chip/zap pull request #1418
Opened 2024-09-04 14:36 UTC by dhchandw

#1382

2024-09-05 13:51 UTC, tbrkollar commented on src/components/ZclEndpointCard.vue
> +              Endpoint - {{ getFormattedEndpointId(endpointReference) }}</strong
remove "Endpoint -" text and add "#" character. I think it was a rebase conflict.

2024-09-05 13:51 UTC, tbrkollar commented on src/components/ZclEndpointCard.vue
> +      <router-link :to="'/'" class="no-decoration">
not use router-link for this. add @click="" handler and a function for this in a script tag.

2024-09-05 13:51 UTC, tbrkollar commented on src/components/ZclEndpointCard.vue
> +  .no-decoration {
if you use a function it is not necessary

2024-09-05 14:35 UTC, dhchandw commented
use this.router.push instead

2024-09-05 16:06 UTC, brdandu requested changes

2024-09-05 16:06 UTC, brdandu commented on src/components/ZclEndpointCard.vue
> +    handleEndpointCardClick(endpointReference) {
When do we put a function on common-mixing vs here? If more than one places calls this function?
Add comments to this method?

2024-09-06 19:24 UTC, brdandu approved these changes

2024-09-06 20:00 UTC, merged