Take into consideration transitive dependencies, not just root struct fields
project-chip/zap pull request #1501
Opened 2024-12-23 20:08 UTC by gmarcosb

Fix for https://github.com/project-chip/zap/issues/1500

2025-01-02 21:34 UTC, bzbarsky-apple requested changes

2025-01-02 21:34 UTC, bzbarsky-apple commented on src-electron/generator/helper-zcl.js
> +          st.struct_has_fabric_sensitive_fields = true
This is wrong, given how this boolean actually gets used.  It really is about the specific fields of this struct, not other things inside it.

In general, having non-toplevel structs with fabric-sensitive fields is not really defined in the spec, and not supported in implementation; if we want to support it we need to figure out how it should work.

2025-01-02 21:34 UTC, bzbarsky-apple commented on src-electron/generator/helper-zcl.js
> +          let sis = await queryZcl.selectAllStructItemsByStructName(
Struct name is not unique; you need to know which cluster is involved too, no?

Furthermore, the same name could be a struct or some other type too (especially across clusters).

2025-01-02 21:35 UTC, bzbarsky-apple commented
This PR and changeset need a _much_ clearer explanation of what is actually being changed and why.

2025-01-02 21:39 UTC, gmarcosb commented on src-electron/generator/helper-zcl.js
> +          st.struct_has_fabric_sensitive_fields = true
>  having non-toplevel structs with fabric-sensitive fields is not really defined in the spec, and not supported in implementation

If this is the case, then this is not wrong? i.e. the behavior is undefined, with or without this change?

2025-01-02 21:49 UTC, gmarcosb commented on src-electron/generator/helper-zcl.js
> +          let sis = await queryZcl.selectAllStructItemsByStructName(
Ouch, thanks for catching that, this was copied from the `checkForDoubleNestedArray` clause below, which apparently has this bug

Do you know if there's already a utility which selects the best match for a struct? i.e. within same cluster if it exists, global otherwise? If there isn't one, I'll write one up

2025-01-02 21:56 UTC, gmarcosb commented
> This PR and changeset need a _much_ clearer explanation of what is actually being changed and why.

@bzbarsky-apple I added some more this morning after discussion in zap channel - I wasn't sure how to explain this except to point to the existing compilation fail & why it's failing.

Was there something specifically you wanted me to address?

2025-01-03 06:13 UTC, brdandu requested changes

2025-01-03 06:13 UTC, brdandu commented on src-electron/generator/helper-zcl.js
> +          let sis = await queryZcl.selectAllStructItemsByStructName(
selectStructByNameAndClusterId

2025-01-03 15:39 UTC, brdandu requested changes
Please update one of the xml files and add a unit test for this as well.

2025-01-03 23:10 UTC, gmarcosb commented
> Please update one of the xml files and add a unit test for this as well.

I added some structs to `zcl-builtin/matter/data-model/chip/test-cluster.xml`, as `partials/cluster-objects-struct.zapt` seemed to be the only test that referenced `struct_contains_array`

2025-01-03 23:11 UTC, gmarcosb commented on src-electron/generator/helper-zcl.js
> +          let sis = await queryZcl.selectAllStructItemsByStructName(
`selectAllStructItemsById` did the trick, but unfortunately there was no way to get the ID of the struct from the `STRUCT_ITEM`, so I had to do some deep surgery to expose that field 🤣

But looks a lot better, thanks for the tip!

2025-01-03 23:14 UTC, gmarcosb commented on src-electron/db/query-zcl.js
> -  (SELECT DATA_TYPE.NAME FROM DATA_TYPE WHERE DATA_TYPE.DATA_TYPE_ID = STRUCT_ITEM.DATA_TYPE_REF) AS TYPE,
I made this change which is slightly unrelated & more of a cleanup, but makes my changes clearer

i.e. I don't understand why there was a sub-query here to select `DATA_TYPE.NAME`, when we were already joining with `DATA_TYPE` & selecting `DATA_TYPE.NAME` -> `dataTypeReferenceName` (which was completely unused but would have the same value)

2025-01-06 10:47 UTC, brdandu requested changes

2025-01-06 10:47 UTC, brdandu commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
Do not change any of the dbmappings because that any existing helper could be using these in the .zapt templates and those will get broken. If you need a new key then just add to an existing dbmap with a different key name from the ones present currently. 
Also, some of the dbmaps which are named after the tables actually should have only the table columns in the dbmap. If you intend to add new keys to the dbmap then it is a good idea to create a new db map with the 'extended' postfix in the name where you can add the columns from the joined tables.

2025-01-06 10:47 UTC, brdandu commented on src-electron/db/query-zcl.js
> -  DATA_TYPE.NAME AS DATA_TYPE_REF_NAME,
This could break the templates for backwards compatibility.

2025-01-06 10:47 UTC, brdandu commented on zcl-builtin/matter/data-model/chip/test-cluster.xml
> +    <item name="a" type="NestedStructList" optional="false"/>
Could you add a test for the helper which will be taking this into account? If zcl_structs then add a generation test for that.

2025-01-06 17:05 UTC, bzbarsky-apple commented on src-electron/generator/helper-zcl.js
> +          st.struct_has_fabric_sensitive_fields = true
Looking for fabric-sensitive bits in non-toplevel structs and assigning semantics to it means that if someone does add something like this, no red flags will go up to actually define it.

We should not change the fabric-sensitive behavior here.

2025-01-06 17:05 UTC, bzbarsky-apple commented on src-electron/generator/helper-zcl.js
> +            i.dataTypeReference
But `i` is an array, not a struct, no?  Is the dataTypeReference here actually correct?  Where is it coming from, exactly?  @brdandu please check whether the query changes above handle this correctly.

2025-01-06 17:05 UTC, bzbarsky-apple commented on zcl-builtin/matter/data-model/chip/test-cluster.xml
> +  <struct name="DeepNestedStructList">
OK, but shouldn't we be testing that the boolean for "contains array" actually gets set for this struct?  Where are we testing that?

2025-01-06 17:34 UTC, gmarcosb commented on src-electron/generator/helper-zcl.js
> +          st.struct_has_fabric_sensitive_fields = true
OK cool, fair enough, easy enough to exclude fabric-sensitive (though it does seem like either way it'll be broken)

2025-01-06 17:40 UTC, gmarcosb commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
No helper is using these (I checked), and these fields are deceiving as they are calculating an already existing value

See my other comment: https://github.com/project-chip/zap/pull/1501#discussion_r1902229928

2025-01-06 17:41 UTC, gmarcosb commented on src-electron/db/query-zcl.js
> -  DATA_TYPE.NAME AS DATA_TYPE_REF_NAME,
No templates use these values (& rightfully so, they're junk values, see https://github.com/project-chip/zap/pull/1501#discussion_r1902229928)

2025-01-06 17:43 UTC, gmarcosb commented on zcl-builtin/matter/data-model/chip/test-cluster.xml
> +    <item name="a" type="NestedStructList" optional="false"/>
The issue is that I could not find any test which was verifying the functionality of `struct_contains_array` - the best I found was 

My thought would be to modify said test to also check for transitive structures - can you point me to said test?

(see also https://github.com/project-chip/zap/pull/1501#issuecomment-2569920792)

2025-01-06 17:45 UTC, gmarcosb commented on src-electron/generator/helper-zcl.js
> +            i.dataTypeReference
Reverted changes to fabric-sensitive bits

`i` is the result of `selectAllStructsWithItems`, i.e. a `structItem` (see `db-mapping.js`)

The changes here must be correct, because all tests pass - unless the tests are no good 😅🤣

In which case that should be addressed separately

2025-01-06 17:47 UTC, gmarcosb commented on zcl-builtin/matter/data-model/chip/test-cluster.xml
> +  <struct name="DeepNestedStructList">
The real question is: where are we testing `struct_contains_array` behavior

Wherever that test is, it should be expanded to also test that it applies transitively

This is the only reference I found to `struct_contains_array` - see https://github.com/project-chip/zap/pull/1501#issuecomment-2569920792

(these zap tests are incredibly hard to grok)

2025-01-07 11:06 UTC, brdandu requested changes

2025-01-07 11:12 UTC, brdandu commented
A couple of templates using struct_contains_array that I saw were `cluster-objects-struct.zapt` , `struct.zapt` and `type-by-cluster.zapt` . Another place to add the struct contains array test can be to update type-by-cluster.zapt and geo-meta.test.js => `epc = genResult.content['type-by-cluster.h']`

2025-01-07 17:44 UTC, gmarcosb commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
I have to push back a bit here, because I think this is precisely what leads to unmaintainable code

Yes, I understand that there can always be unforeseen cases - every code change comes with risk.

But code which makes no sense should fall in one of 2 categories:

1) Dead code which should be removed ASAP
2) Unintuitive code that should be well-tested & have good test coverage

Going the route of "cleaning things up could lead to problems, so let's just continue to build debt" is precisely what leads to unmaintainable code

The worst that will happen here is that some template will break & we'll get a compile-time error, correct? If that happens, we rollback & add the respective test coverage?

That seems like a worthwhile risk to move us towards more maintainable & cleaner code

2025-01-07 17:45 UTC, gmarcosb commented on src-electron/db/query-zcl.js
> -  DATA_TYPE.NAME AS DATA_TYPE_REF_NAME,
My general experience is that lots of good deeds result in moving the needle in a positive direction

Yes, sometimes they lead to bugs in unforeseen cases

But the alternative, letting debt build up because it's scary to clean things up, leads to more issues over time

2025-01-07 17:59 UTC, gmarcosb commented on zcl-builtin/matter/data-model/chip/test-cluster.xml
> +    <item name="a" type="NestedStructList" optional="false"/>
Thanks for the pointer! Test added

2025-01-07 18:02 UTC, gmarcosb commented on zcl-builtin/matter/data-model/chip/test-cluster.xml
> +  <struct name="DeepNestedStructList">
`struct_contains_array` had no test coverage, that's why I couldn't find it.   Tests added now to both cover transitive as well as at root

2025-01-07 18:07 UTC, paulr34 commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
That sounds fine to me

2025-01-07 18:21 UTC, paulr34 commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
Here is how it could be broken:

- Matter developer has SDK version x.x.x which they were promised works with the chips they bought.
- SDK version x.x.x was created with ZAP version X which is older than ZAP version Y 
- SDK version x.x.x has external helpers referencing this variable
- If Matter developers updates ZAP to version Y their external helper will not return the correct value

That is a legitimate risk but at the same time I agree with you that we should not be maintaining duplicate data. We would need to determine how relevant that risk really is. 

There is a non zero chance that this would break dev environments and people will be angry.

2025-01-07 18:27 UTC, gmarcosb commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
If they're running SDK version x.x.x, seems they should stay with ZAP version X

ZAP version & SDK version should be lockstep (this is generally true, which comes back to the argument we brought up before about the issues with the repos being separate)

There doesn't seem to be a valid use-case to update ZAP while not updating the SDK version

If someone does this & are upset, send them my way & I can talk to them about how ZAP & SDK should be updated together, as they are inter-dependent

In this case specifically (as there are no refs to these other 2 fields in SDK), I can also inform them that their current use of these fields is probably not having the desired effect, because they have always had the same value as `type` - that should allow them to do some cleanup as well

2025-01-07 18:27 UTC, paulr34 approved these changes

2025-01-07 18:28 UTC, paulr34 commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
Approved

2025-01-09 12:22 UTC, brdandu commented on src-electron/db/db-mapping.js
> -      dataTypeReference: x.TYPE,
`If they're running SDK version x.x.x, seems they should stay with ZAP version X` -> When an issue is logged by a user for zap and we fix it then we do not request the user to update the SDK. It will be better out of box experience for users to just get the latest ZAP. From personal experience, I can say this is generally appreciated by users even though it is more work for the ZAP team.
Also, Please note that we also use ZAP internally for our own SDKs(Zigbee apart from Matter for us). I had to go through every release of ours in the last 2-3 years to see if either of the 2 keys were used anywhere. Hopefully I did not miss a release due to branch naming conventions which can change sometimes. Since I could not find an issue in this case yet, I can approve it but I can assure you backwards compatibility promises are not easy to maintain and it is not always feasible to do these checks. If an issue comes because of this in an old SDK application then it is not easy to backtrack and figure this issue out because it can get pretty crazy to backtrack.
It is my request to only add new keys unless we are really doing an all out cleaning. Even before cleaning up we will need to throw a warning that these dead keys will no longer be supported from the next release.

2025-01-09 19:01 UTC, bzbarsky-apple approved these changes

2025-01-09 19:01 UTC, bzbarsky-apple commented on src-electron/generator/helper-zcl.js
> +    const checkTransitive = async (items) => {
```suggestion
    const checkForArraysTransitively = async (items) => {
```

2025-01-09 21:14 UTC, gmarcosb commented on src-electron/generator/helper-zcl.js
> +              .then((sis) => {
Went with the other one (couldn't remember if one could just pass methods as lambdas in JS 😅)

2025-01-10 19:18 UTC, merged