new: added support for cluster shutdown functions
project-chip/zap pull request #921
Opened 2023-02-09 17:25 UTC by rochaferraz

As discussed on https://github.com/project-chip/connectedhomeip/pull/24844, we should have some type of callback that is able to called to shutdown pending timers on clusters that are being torn down.

This code adds `MatterXXClusterServerShutdownCallback` in the same way zap generates callbacks to `emberAfXXClusterServerInitCallback`

@bzbarsky-apple @andy31415

2023-02-09 19:06 UTC, bzbarsky-apple requested changes

2023-02-10 03:12 UTC, bzbarsky-apple commented
With https://github.com/project-chip/zap/pull/922 this is going to need a tweak to the logic to use the config data, and the list will just go into the yaml on the Matter side.

2023-02-10 18:13 UTC, rochaferraz commented on src-electron/generator/matter/app/zap-templates/templates/app/helper.js
> +      if (endpointClusterWithShutdown.includes(clusterName)) {
That's true. They need to be in order. Changed and tested with the matter branch, the shutdowns are called correctly from `shutdownEndpoint`

2023-02-10 18:33 UTC, bzbarsky-apple approved these changes
Approving, but this needs a rebase....

2023-02-10 20:31 UTC, andy31415 approved these changes

2023-02-11 00:30 UTC, merged